const fs=require('fs');const assert=require('assert');const {JSDOM,VirtualConsole}=require('jsdom');
(async()=>{const base=process.argv[2]||'.qa-chs';const responses=JSON.parse(fs.readFileSync(base+'/ui-fixtures.json','utf8'));let response;
let errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync(base+'/chs-rendered.html','utf8'),{runScripts:'dangerously',url:'http://localhost/chs',virtualConsole:vc,beforeParse(w){w.HTMLElement.prototype.scrollIntoView=()=>{};w.fetch=async()=>({ok:response.ok,json:async()=>response});}});const w=dom.window,d=w.document;
for(response of responses){d.getElementById('career').value=response.career;d.getElementById('grade').value=response.grade;await d.getElementById('go').onclick();assert.equal(d.getElementById('error').textContent,'');assert.ok(d.getElementById('results').classList.contains('show'));assert.equal(d.querySelectorAll('.course').length,response.chs.primary_course_details.length+response.chs.supporting_course_details.length+response.chs.future_course_details.length);assert.equal(d.getElementById('futureCourses').hidden,response.grade==='12');assert.equal(d.querySelectorAll('#steps .roadstep').length,response.steps.length);assert.equal(d.getElementById('go').disabled,false);assert.ok(!d.getElementById('results').textContent.includes('undefined'));}
response={ok:false,error:'Test service unavailable'};await d.getElementById('go').onclick();assert.equal(d.getElementById('error').textContent,response.error);assert.ok(!d.getElementById('results').classList.contains('show'));assert.equal(d.getElementById('go').disabled,false);
response=JSON.parse(JSON.stringify(responses[0]));response.chs.primary_course_details[0].why='<img src=x onerror=alert(1)>';await d.getElementById('go').onclick();assert.equal(d.querySelectorAll('#courses img').length,0);assert.ok(d.getElementById('courses').textContent.includes('<img'));
const admin=new JSDOM(fs.readFileSync(base+'/admin-rendered.html','utf8'),{runScripts:'outside-only'});for(const [i,s] of [...admin.window.document.querySelectorAll('script')].entries()){new (require('vm').Script)(s.textContent,{filename:`admin-${i}.js`});}
assert.deepEqual(errors,[]);console.log('PASS: 15 priority career/grade result renders; visible prerequisites/supporting courses; grade 12 layout; failure hides stale results; button recovery; escaping; administrator JavaScript syntax. DOM checks only, not browser screenshot QA.');dom.window.close();admin.window.close();})().catch(e=>{console.error(e);process.exit(1)});
